#!/usr/bin/env python3

import time
import json
import sys
import os

def filesize_ex(s):
  if s >= 1024*1024*1024:
    return s/(1024*1024*1024), 'G'
  elif s >= 1024*1024:
    return s/(1024*1024), 'M'
  elif s >= 1024:
    return s/1024, 'K'
  else:
    return s, ''

def get_data():
  iface = None

  with open('/proc/net/route') as f:
    next(f)
    for line in f:
      dev, route, *_ = line.split()
      if route == '00000000':
        iface = dev
        break

  if not iface:
    return None, None, None

  iface += ':'
  with open('/proc/net/dev') as f:
    next(f)
    next(f)
    for line in f:
      data = line.split()
      dev, recv, *_ = data
      send = data[9]
      if dev == iface:
        return iface.rstrip(':'), int(recv), int(send)

  return None, None, None

COLORS = {
  '': '#6c7086',
  'K': '#5798d9',
  'M': '#57d977',
  'G': '#9857d9',
}

def format_size(s):
  f, u = filesize_ex(s)
  if u:
    t = f'{f:.1f}{u}'
  else:
    t = f'{f:.0f}'
  c = COLORS.get(u, '#9857d9')
  return f'<span color="{c}">{t}</span>'

def main():
  iface, last_recv, last_send = get_data()
  
  if not iface:
    output = {"text": "<span color='#f38ba8'>No Net</span>", "tooltip": "No network interface"}
    json.dump(output, sys.stdout)
    print()
    return

  time.sleep(0.1)

  while True:
    _, recv, send = get_data()
    
    if recv is not None and last_recv is not None:
      down = recv - last_recv
      up = send - last_send
      
      down_fmt = format_size(down)
      up_fmt = format_size(up)
      
      output = {
        "text": f'{down_fmt}↓ {up_fmt}↑',
        "tooltip": f"{iface}: ↓{down} ↑{up}"
      }
    else:
      output = {"text": "..."}

    json.dump(output, sys.stdout)
    print(flush=True)
    
    last_recv = recv
    last_send = send
    time.sleep(1)

if __name__ == '__main__':
  main()