#!/usr/bin/env python3

import sys
import json
from functools import partial
import argparse

try:
  import dbus
  from dbus.mainloop.glib import DBusGMainLoop
  from gi.repository import GLib
  HAS_DBUS = True
except ImportError:
  HAS_DBUS = False

data = {"text": "", "tooltip": "", "class": "", "percentage": 0 }

def handle_active(a):
  title, app_id, output = a
  data['text'] = title
  data['tooltip'] = app_id
  json.dump(data, sys.stdout, ensure_ascii=False)
  print(flush=True)

def prop_changed(output, _iface, x, _sig):
  if a := x.get('active'):
    if a[2] == output:
      handle_active(a)

def main(output):
  if not HAS_DBUS:
    output = {"text": "taskmaid: no dbus", "tooltip": "Install python-dbus and pygobject", "class": "", "percentage": 0}
    json.dump(output, sys.stdout)
    print(flush=True)
    return

  DBusGMainLoop(set_as_default=True)

  bus = dbus.SessionBus()
  try:
    obj = bus.get_object('me.lilydjwg.taskmaid', '/taskmaid', follow_name_owner_changes=True)
    prop = dbus.Interface(obj, dbus_interface='org.freedesktop.DBus.Properties')
    try:
      a = prop.Get('me.lilydjwg.taskmaid', 'active')
      if a[2] == output:
        handle_active(a)
    except dbus.exceptions.DBusException:
      pass
    prop.connect_to_signal('PropertiesChanged', partial(prop_changed, output))

    loop = GLib.MainLoop()
    try:
      loop.run()
    except KeyboardInterrupt:
      print()
      sys.exit(130)
  except dbus.exceptions.DBusException:
    output = {"text": "", "tooltip": "", "class": "", "percentage": 0 }
    json.dump(output, sys.stdout)
    print(flush=True)

def close_active():
  if not HAS_DBUS:
    print("Error: dbus not available", file=sys.stderr)
    return

  bus = dbus.SessionBus()
  obj = bus.get_object('me.lilydjwg.taskmaid', '/taskmaid')
  maid = dbus.Interface(obj, dbus_interface='me.lilydjwg.taskmaid')
  maid.CloseActive()

if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='taskmaid integration for waybar')
  parser.add_argument('output',
                      help='the output (monitor) this instance is for')
  args = parser.parse_args()

  if args.output == 'close':
    close_active()
  else:
    main(args.output)